<a href="https://colab.research.google.com/github/Paladin-88/data-science/blob/main/%D0%9B%D0%B8%D0%BD%D0%B5%D0%B9%D0%BD%D0%B0%D1%8F_%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F_%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C%2C_%D0%BF%D0%BE%D0%B7%D0%B2%D0%BE%D0%BB%D1%8F%D1%8E%D1%89%D0%B0%D1%8F_%D0%BF%D1%80%D0%BE%D0%B3%D0%BD%D0%BE%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C_%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE_%D0%BA%D0%BB%D0%B8%D0%BA%D0%BE%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Отчет составил: Наумов Михаил Андреевич

1.	Проанализируйте распределения признаков, которые вы хотите включить в модель. НЕ забывайте о требованиях линейной регрессионной модели к типам данных и к особенностям распределения признаков.

2.	Проанализируйте взаимосвязи между признаками, которые вы хотите включить в модель. Не забывайте, что для того, чтобы модель имела смысл, необходимо включать в модель такие независимые признаки (предикторы), которые связаны с откликом (зависимой переменной) и не связаны между собой.

3.	Постройте уравнение регрессии с участием тех переменных, которые Вы решили включить в модель. Составляя уравнение на основе полученных коэффициентов, помните о разнице между стандартизованными и нестандартизованными коэффициентами, а также об оценке значимости вклада признаков в модель.

4.	Оцените качество модели любыми способами, которые считаете приемлемыми. Выполняя эту часть задания, помните о важности анализа не только коэффициента детерминации, но и регрессионных остатков.

5.	Кратко опишите 2-3 ключевых признака, которые вносят наибольший вклад в дисперсию отклика. 

Как можно описать их взаимосвязь с откликом? 
Какие изменения приводят к увеличению количества кликов, которые получают организации той или иной рубрики? 
Какие рекомендации вы могли бы сформулировать на основе построенной модели?

Приложение:
1. Файл данных: https://d3c33hcgiwev3.cloudfront.net/_42d93fac81d0a92a275e25bdc4891ca1_Data_Projects.csv
2. Описание переменных: https://d3c33hcgiwev3.cloudfront.net/_29dfde6117dcd5724b7d2cd4f80cd5a6_Data_description.pdf

In [ ]:
import numpy as np # линейная алгебра
import pandas as pd # обработка данных, CSV afqk I/O (например pd.read_csv)
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [ ]:
data = pd.read_csv('D:\_42d93fac81d0a92a275e25bdc4891ca1_Data_Projects.csv', sep=';', decimal=',') # считываем датасет
data.head(10) # выводим первые 10 значенией

,AddressCount,CallsCount,ClicksCount,FirmsCount,GeoPart,MobilePart,UsersCount,Distance,IsGeo
0,156,20,1903,176,0.416104,0.535762,1125,749.966084,1
1,17,37,258,20,0.211679,0.430657,157,2289.032424,0
2,78,56,1956,185,0.349475,0.476594,1195,1423.376512,1
3,14,70,378,19,0.318718,0.463744,206,3396.566089,0
4,111,90,4089,90,0.556175,0.490573,2934,1576.514154,1
5,53,96,1669,162,0.398978,0.421737,991,2337.603777,0
6,18,137,373,26,0.407108,0.389338,180,2780.961789,0
7,9,150,563,15,0.187886,0.175525,265,5206.838454,0
8,56,153,1366,56,0.335469,0.498856,613,2704.490401,0
9,371,176,5913,31,0.288146,0.608774,3981,4333.989691,0

In [ ]:
# Переводим стороковые значения в числовые 
pd.to_numeric(data['AddressCount'])
pd.to_numeric(data['CallsCount'])
pd.to_numeric(data['ClicksCount'])
pd.to_numeric(data['FirmsCount'])
pd.to_numeric(data['GeoPart'])
pd.to_numeric(data['MobilePart'])
pd.to_numeric(data['UsersCount'])
pd.to_numeric(data['Distance'])

0      749.966084
1     2289.032424
2     1423.376512
3     3396.566089
4     1576.514154
         ...
74    1908.108110
75    2642.200165
76    2278.162917
77     989.412139
78     918.713972
Name: Distance, Length: 79, dtype: float64

In [ ]:
data.head(20) # выводим первые 20 значенией

,AddressCount,CallsCount,ClicksCount,FirmsCount,GeoPart,MobilePart,UsersCount,Distance,IsGeo
0,156,20,1903,176,0.416104,0.535762,1125,749.966084,1
1,17,37,258,20,0.211679,0.430657,157,2289.032424,0
2,78,56,1956,185,0.349475,0.476594,1195,1423.376512,1
3,14,70,378,19,0.318718,0.463744,206,3396.566089,0
4,111,90,4089,90,0.556175,0.490573,2934,1576.514154,1
5,53,96,1669,162,0.398978,0.421737,991,2337.603777,0
6,18,137,373,26,0.407108,0.389338,180,2780.961789,0
7,9,150,563,15,0.187886,0.175525,265,5206.838454,0
8,56,153,1366,56,0.335469,0.498856,613,2704.490401,0
9,371,176,5913,31,0.288146,0.608774,3981,4333.989691,0
10,9552,207,101558,1473,0.383507,0.705315,54098,813.439315,1
11,42,222,1154,64,0.223269,0.139612,410,4511.632303,0
12,84,228,1031,39,0.310968,0.237456,578,6272.751840,0
13,48,237,1307,14,0.203375,0.669183,596,3969.150362,1
14,30,256,1139,114,0.318486,0.231626,550,4149.002902,0
15,70,270,976,132,0.246795,0.133974,537,4522.585897,0
16,73,278,2805,42,0.322342,0.440951,1196,2775.018152,0
17,258,310,3970,245,0.313795,0.458652,2344,893.981377,1
18,61,319,1316,168,0.367380,0.343316,558,1033.112765,0
19,66,344,1478,35,0.092917,0.090000,500,5528.065546,0

In [ ]:
data.info() # получаем информацию о датасете и его значениях

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   AddressCount  79 non-null     int64
 1   CallsCount    79 non-null     int64
 2   ClicksCount   79 non-null     int64
 3   FirmsCount    79 non-null     int64
 4   GeoPart       79 non-null     float64
 5   MobilePart    79 non-null     float64
 6   UsersCount    79 non-null     int64
 7   Distance      79 non-null     float64
 8   IsGeo         79 non-null     int64
dtypes: float64(3), int64(6)
memory usage: 5.7 KB

In [ ]:
data.describe() # выволим информацию о основных статических показателях датасета

,AddressCount,CallsCount,ClicksCount,FirmsCount,GeoPart,MobilePart,UsersCount,Distance,IsGeo
count,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000,79.000000
mean,1048.037975,3648.683544,21826.012658,305.088608,0.342645,0.445746,9753.126582,2669.426352,0.354430
std,1642.066119,8124.105402,32474.959513,382.052090,0.103608,0.146131,13927.295721,1427.785304,0.481397
min,9.000000,20.000000,258.000000,14.000000,0.092917,0.090000,157.000000,714.787236,0.000000
25%,81.000000,346.000000,2055.000000,71.500000,0.281527,0.357293,1167.500000,1562.103740,0.000000
50%,371.000000,931.000000,6921.000000,185.000000,0.322342,0.463744,2934.000000,2586.503274,0.000000
75%,1195.000000,2457.500000,30625.500000,402.500000,0.416907,0.551654,13265.000000,3575.692331,1.000000
max,9552.000000,48497.000000,167155.000000,2379.000000,0.556175,0.737288,61127.000000,6292.207311,1.000000

In [ ]:
x = np.array((data['ClicksCount'])).reshape((-1, 1)) # Определяем данные, с которыми предстоит работать. 
y = np.array(data['FirmsCount'])                     # Входы (регрессоры, x) и выход (предиктор, y) должны 
                                                     # быть массивами (экземпляры класса numpy.ndarray)
    
    
""" Теперь у вас два массива: вход x и выход y. Нужно вызвать .reshape()на x, потому что этот массив 
должен быть двумерным или более точным – иметь одну колонку и необходимое количество рядов. Это как 
раз то, что определяет аргумент (-1, 1).
"""

print(x)
print(y)

# Вот как x и y выглядят теперь:

[[  1903]
 [   258]
 [  1956]
 [   378]
 [  4089]
 [  1669]
 [   373]
 [   563]
 [  1366]
 [  5913]
 [101558]
 [  1154]
 [  1031]
 [  1307]
 [  1139]
 [   976]
 [  2805]
 [  3970]
 [  1316]
 [  1478]
 [  2969]
 [  2103]
 [  1763]
 [  1568]
 [  2007]
 [  2473]
 [  3913]
 [  2293]
 [  1383]
 [  4379]
 [  2760]
 [  3398]
 [  6814]
 [  1969]
 [  7833]
 [  9145]
 [  7416]
 [  2690]
 [  2603]
 [  3760]
 [  3945]
 [  4623]
 [ 49467]
 [ 24423]
 [  5564]
 [  9604]
 [  6921]
 [ 34467]
 [ 42044]
 [ 20841]
 [  7382]
 [ 31457]
 [ 10638]
 [ 14267]
 [  8051]
 [ 19176]
 [ 27544]
 [  8523]
 [  9250]
 [ 19231]
 [ 24755]
 [ 64645]
 [ 40841]
 [ 31861]
 [ 29794]
 [ 19935]
 [ 26834]
 [ 75789]
 [ 60327]
 [ 56592]
 [ 56280]
 [ 38640]
 [ 94918]
 [ 66822]
 [ 44597]
 [ 33388]
 [ 75303]
 [167155]
 [149920]]
[ 176   20  185   19   90  162   26   15   56   31 1473   64   39   14
  114  132   42  245  168   35   84  185   51   59   33  195  201   98
   93   48   44  157  300   96  341  443  347   79   54   22   19  136
 2379  287  197   52  268  328  350  632  548  806  363  124  143  270
  224  192  142  227  447  558  197  583  790   82  545  740  438  598
  456  396  797  205  113  411  409 1457 1157]

In [ ]:
model = LinearRegression().fit(x, y) # экземпляр класса LinearRegression, представляе модель регрессии

# С помощью .fit() вычисляются оптимальные значение весов b₀ и b₁, используя существующие вход и выход (x и y) 
# в качестве аргументов. Другими словами, .fit() совмещает модель. Она возвращает self - переменную model

In [ ]:
#После совмещения модели нужно убедиться в удовлетворительности результатов для интерпретации.
>>> r_sq = model.score(x, y) # определени коэффициента детерминациис помощью .score(), вызванной на model
>>> print('Коэффициент детерминации', r_sq)

Коэффициент детерминации 0.5111948662703459

In [ ]:
#.score() принимает в качестве аргументов предсказатель x и регрессор y, и возвращает значение R².

# model содержит атрибуты .intercept_, который представляет собой коэффициент b₀ с .coef_- b₁:
print('b₀:', model.intercept_) # скаляр
print('b₁:', model.coef_)      # массив

b₀: 121.50174226329591
b₁: [0.00841138]

# Прогнозируем  количество кликов в организации той или иной рубрики

In [ ]:
# Прогнозируем количество кликов, используя .predict()
y_pred = model.predict(x)
print('Прогнозируемое количество кликов:', y_pred, sep='\n')

Прогнозируемое количество кликов:
[ 137.50859657  123.67187805  137.95439966  124.68124354  155.89587115
  135.54033388  124.63918664  126.23734866  132.99168603  171.23822651
  975.74457449  131.20847367  130.17387405  132.49541466  131.08230299
  129.7112482   145.09566046  154.89491704  132.57111708  133.93376048
  146.47512662  139.19087238  136.33100351  134.69078459  138.38337999
  142.30308262  154.41546843  140.78903439  133.13467947  158.33517107
  144.71714841  150.08360823  178.81687902  138.06374759  187.38807426
  198.42380356  183.8805292   144.12835187  143.3965619   153.12852744
  154.68463256  160.38754755  537.58742908  326.93285248  168.30265522
  202.28462653  179.71689658  411.41674353  475.14976249  296.80329277
  183.59454231  386.09849263  210.98199246  241.50688698  189.22175489
  282.79834667  353.18476645  193.19192579  199.30699835  283.26097252
  329.72543032  665.2553401   465.03087351  389.49668976  372.11036929
  289.18258336  347.21268734  758.99174809  628.93500542  597.51850472
  594.89415446  446.51742825  919.89301768  683.56691226  496.62401317
  402.34086555  754.90381788 1527.50580517 1382.53568747]

 ## Вывод:

#### На основе полученных данных можно сделать вывод, что количество кликов зависиит от рубрики, в которовой указана органищациия. Для увеличения кликов организации можно посоветовать:
1. изменить или дополнительно указать другую более кликабельную рубрику, возможно даже несколько; 
2. приобретение топовых позиций в рубрике;
3. приобрести дополнильные рекламные услуги, позволяющие выделить ее среди других компаний в сервисе.

# Отчет составил: Наумов Михаил Андреевич